### ISSUE TITLE
Comment out example entrypoints in setup.cfg

### ISSUE THREAD

**Issue by jesper-friis** [EMMC-ASBL/oteapi-plugin-template#23]
Since the provided strategies are examples, we don't want to distribute them by default. I will therefore suggest that we simply comment out all default entry points in setup.cfg. 

We could add a comment at the top of the file saying "Uncomment the entry points you want to distribute."

**Comment by CasperWA** [comment]
The point of this repository is to be a template. To me that means it should show the best practices and examples of how each of the strategy types can be implemented.

As a comment, one can not "pollute" the plugin space by generating a package form this template - one needs to install this in an environment first.
I think it's fine to have the `setup.cfg` file as is, uncommented, but with some clear example of how it's supposed to look.
But one can of course go the other way as well. In the end we should have two things: Great documentation on how to use this template, possibly with a step-by-step tutorial on creating a plugin & then an example repository generated using this template to implement some standard strategies - like for a built-in executable in Linux distros or something?

**Comment by francescalb** [comment]
I agree with Jesper that they shold be commented out because having them uncommented incraeses the risk that developers do not delete them and we end up with clashing (demo)strategies from different plugins.
